ios release tweaks

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,6 +1,8 @@
 workflows:
   ios-distribute:
     name: iOS Distribute Workflow
+    integrations:
+      app_store_connect: Codemagic-key
     environment:
       vars:
         XCODE_WORKSPACE: "ios/App/App.xcworkspace"
@@ -9,10 +11,6 @@ workflows:
         TEAM_ID: "H9A4H444G4"
       groups:
         - Papricut
-      app_store_connect:
-        key_id: $APP_STORE_CONNECT_KEY_ID
-        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
-        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
     triggering:
       events:
         - push
@@ -38,17 +36,17 @@ workflows:
         script: |
           echo "📦 Archiving the app..."
           xcodebuild -workspace "$XCODE_WORKSPACE" \
-                    -scheme "$XCODE_SCHEME" \
-                    -sdk iphoneos \
-                    -configuration Release \
-                    -archivePath "$HOME/build/App.xcarchive" \
-                    -allowProvisioningUpdates \
-                    -destination 'generic/platform=iOS' \
-                    DEVELOPMENT_TEAM="$TEAM_ID" \
-                    archive || {
-                      echo "❌ Archive failed.";
-                      exit 1;
-                    }
+                     -scheme "$XCODE_SCHEME" \
+                     -sdk iphoneos \
+                     -configuration Release \
+                     -archivePath "$HOME/build/App.xcarchive" \
+                     -allowProvisioningUpdates \
+                     -destination 'generic/platform=iOS' \
+                     DEVELOPMENT_TEAM="$TEAM_ID" \
+                     archive || {
+                       echo "❌ Archive failed.";
+                       exit 1;
+                     }
 
           echo "📤 Exporting the IPA..."
           xcodebuild -exportArchive \
@@ -76,7 +74,8 @@ workflows:
 
       - name: Upload to App Store Connect
         script: |
-          app-store-connect-publisher submit \
+          app-store-connect-publisher \
+            submit \
             --path "$HOME/build/ipa/"*.ipa \
             --platform ios \
             --api-key Codemagic-key
